# Generated by Django 5.2.3 on 2025-06-26 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0002_alter_exercise_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de la séance')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes de la séance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Séance d'entraînement",
                'verbose_name_plural': "Séances d'entraînement",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, null=True, verbose_name='Séries')),
                ('reps', models.IntegerField(blank=True, null=True, verbose_name='Répétitions')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée (minutes)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Notes spécifiques à l'exercice")),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises_app.exercise', verbose_name='Exercice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to='exercises_app.workoutsession', verbose_name="Séance d'entraînement")),
            ],
            options={
                'verbose_name': "Entrée d'exercice",
                'verbose_name_plural': "Entrées d'exercices",
            },
        ),
    ]
