# Generated by Django 5.2.3 on 2025-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0003_alter_exercise_adaptative_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('null', 'Null')], default='null', max_length=10),
        ),
    ]
