# Generated by Django 5.2.3 on 2025-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0003_workoutsession_exerciseentry'),
        ('sport_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseentry',
            options={'verbose_name': 'Exercice entry', 'verbose_name_plural': 'Exercises entries'},
        ),
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-date'], 'verbose_name': 'Training session', 'verbose_name_plural': 'Trainings sessions'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='adaptative_for',
        ),
        migrations.AddField(
            model_name='exercise',
            name='adaptative_for',
            field=models.ManyToManyField(blank=True, related_name='exercises_adaptive_for', to='sport_profile.constraintfield'),
        ),
    ]
