# Generated by Django 5.2.3 on 2025-07-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_alter_exerciseentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseentry',
            name='session',
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
