# Generated by Django 5.2.3 on 2025-07-04 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0006_exerciseentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseentry',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
