# Generated by Django 5.2.3 on 2025-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0007_exerciseentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('facile', 'Facile'), ('modéré', 'Modéré'), ('difficile', 'Difficile'), ('adaptatif', 'Adaptatif')], default='adaptatif', max_length=50),
        ),
    ]
